### ISSUE TITLE
“文件上传”btn会消失

### ISSUE THREAD

**Issue by sinner77** [ifanrx/react-ueditor#1]
进去/editor页面，页面中的富文本组件一开始没有“文件上传”按钮，手动点击浏览器的刷新，黑色的文件上传按钮又出现了。。。。
请问下是怎么回事
感谢回答

**Comment by YaoKaiLun** [comment]
是每一次进入都会还是只出现一次? 是跑项目的 example 出现还是在你自己的项目中出现的？如果是自己的项目，可以考虑是否是因为生命周期使用错误而造成的。
