### ISSUE TITLE
项目中导入组件，但是在页面上显示不出来

### ISSUE THREAD

**Issue by aa7633285** [ifanrx/react-ueditor#10]
在项目中下载了组件，并且import进来了   但是在下面使用的时候  页面上是空的  只有一个script标签和input标签

**Comment by aa7633285** [comment]
报的是 ueditor.config.js 找不到  但是我的路径是对的啊

**Comment by aa7633285** [comment]
已经搞定了  能显示了  麻烦问一下  支持不支持图片预览的？

**Comment by YaoKaiLun** [comment]
图片预览是指？

**Comment by aa7633285** [comment]
你好，我现在能上传图片和附件，但是附件上传之后 不能在编辑器内看到，不知道你那边封装了这个没有

**Comment by YaoKaiLun** [comment]
目前还不支持附件上传哦

**Comment by aa7633285** [comment]
附件上传这里我已经弄出来了，但是在编辑器里面是不能显示的。。希望楼主能优化一下！！
