### ISSUE TITLE
一个页面上有两个编辑框的话，更改内容只能获取最后一个编辑框内的内容，怎么解决

### ISSUE THREAD

**Issue by aa7633285** [ifanrx/react-ueditor#13]

**Comment by YaoKaiLun** [comment]
可通过 getRef 属性来操作

**Comment by aa7633285** [comment]
麻烦具体说一下

**Comment by YaoKaiLun** [comment]
https://github.com/ifanrx/react-ueditor#%E7%9B%B4%E6%8E%A5%E6%93%8D%E4%BD%9C-ueditor-%E5%AE%9E%E4%BE%8B
