### ISSUE TITLE
页面刷新，编辑框不显示，报404

### ISSUE THREAD

**Issue by aa7633285** [ifanrx/react-ueditor#14]

**Comment by YaoKaiLun** [comment]
什么资源 404 ？

**Comment by aa7633285** [comment]
![qq 20180915095546](https://user-images.githubusercontent.com/37429027/45581280-986eba00-b8cd-11e8-840a-3a495adbf8f6.png)

**Comment by aa7633285** [comment]
刷新就报这个

**Comment by aa7633285** [comment]
并且编辑框不显示了

**Comment by YaoKaiLun** [comment]
看起来像是你的 ueditor 路径配置出错了
