### ISSUE TITLE
项目启动报错

### ISSUE THREAD

**Issue by jonerose** [ifanrx/react-ueditor#15]
引入ifanrx-react-ueditor之后，复制example目录下的App.js到本地项目目录，引入了vendor目录并修改了ueditorPath='./vendor/ueditor'，启动时报
ReactUeditor.js:167 Uncaught (in promise) TypeError: Cannot read property 'getEditor' of undefined
    at ReactUeditor._this.initEditor (ReactUeditor.js:167)；请问这怎么解决啊？🙏

**Comment by YaoKaiLun** [comment]
你试下在控制台，敲  window.UE，看是否能获取到值，如果不能，说明 ueditor 引入出现了问题
