### ISSUE TITLE
插入超链接报错

### ISSUE THREAD

**Issue by wangzhipeng404** [ifanrx/react-ueditor#18]
显示link图标之后，点击就会报id is not defind, 无法插入超链接

**Comment by YaoKaiLun** [comment]
@wangzhipeng404 麻烦下载最新的 1.5.3 再试一下

**Comment by aa7633285** [comment]
插入超链接的配置在哪

**Comment by wangzhipeng404** [comment]
ueditor.config.js 或者初始化时设置toolbars

Fly to sky <notifications@github.com>于2018年11月15日 周四18:06写道：

**Comment by aa7633285** [comment]
插入超链接的配置项英文是什么，我知道在哪里添加。或者说是值是什么

**Comment by wangzhipeng404** [comment]
看ueditor文档啊，好像是link吧

Fly to sky <notifications@github.com>于2018年11月15日 周四18:10写道：

**Comment by wangzhipeng404** [comment]
升级到最新版吧，之前我就是这样才开的这个issue

Fly to sky <notifications@github.com>于2018年11月15日 周四18:26写道：

**Comment by aa7633285** [comment]
"dependencies": {
        "antd": "^3.5.3",
        "axios": "^0.18.0",
        "ifanrx-react-ueditor": "1.5.3",
        "jquery-datetimepicker": "^2.5.20",
        "normalize.css": "^8.0.0",
        "react": "^16.3.2",
        "react-dom": "^16.3.2",
        "react-loadable": "^5.4.0",
        "react-router": "^4.2.0",
        "react-router-dom": "^4.2.2",
        "react-scripts": "^1.1.4"
    },
是1.5.3

**Comment by wangzhipeng404** [comment]
console有报错不

Fly to sky <notifications@github.com>于2018年11月15日 周四18:30写道：

**Comment by aa7633285** [comment]
id is not defind

**Comment by aa7633285** [comment]
还有lang is not defined

**Comment by wangzhipeng404** [comment]
你有更新呢线上的ueditor.all.min.js么，更新一下，清掉本地缓存试试

Fly to sky <notifications@github.com>于2018年11月15日 周四18:32写道：

**Comment by aa7633285** [comment]
现在UEditor还有在维护么

**Comment by aa7633285** [comment]
插入超链接能成功，但是点击不能跳转。这个怎么解决？

**Comment by wangzhipeng404** [comment]
看看源码正常生成a标签了不就得了，生成了发布出去就能跳了

Fly to sky <notifications@github.com>于2018年11月19日 周一10:12写道：

**Comment by wangzhipeng404** [comment]
反正你把内容获取出来插入到展示的地方，看能否跳转不就行了

Fly to sky <notifications@github.com>于2018年11月19日 周一10:25写道：

**Comment by aa7633285** [comment]
那肯定能跳转  我的意思是在编辑框里点击、、、

**Comment by wangzhipeng404** [comment]
暂时没发现ueditor怎么跳转，其他的编辑器有些是可以按ctrl点击跳转

Fly to sky <notifications@github.com>于2018年11月19日 周一10:32写道：
