### ISSUE TITLE
内容过多时，编辑框变的巨长无比，而不是内容以滚动的方式呈现，导致看不到工具栏

### ISSUE THREAD

**Issue by mexiQQ** [ifanrx/react-ueditor#20]

**Comment by YaoKaiLun** [comment]
@mexiQQ 我增加了 onReady 属性，你可以在该事件的回调了调用 ueditor 的方法设置编辑器高度，如下：

```
  handleReady = () => {
    this.ueditor.setHeight(400)
  }
```

不过前提是你要在 getRef 的回调中拿到 ueditor 的实例，具体可参考 example 中的例子：
https://github.com/ifanrx/react-ueditor/blob/master/example/App.js
