### ISSUE TITLE
chrome 49下报错 Invalid regular expression flags

### ISSUE THREAD

**Issue by wangzhipeng404** [ifanrx/react-ueditor#21]
chome 49版本下初始化错误：
Uncaught SyntaxError:  Invalid regular expression flags       ueditor.all.min.js:8
Unhanlded promise rejection TypeError: window.UE.getEditor is not a funtion

因为客户还要一部分是xp系统，xp下chrome已经不更新，只能到49版本，希望能有支持一下这个版本

**Comment by YaoKaiLun** [comment]
@wangzhipeng404 不好意思，我是在 Mac 下进行开发的，目前没有 Windows 设备，你可以提供一下具体的报错信息，我这边尝试修复一下，也欢迎你提 PR : )  https://github.com/ifanrx/react-ueditor#%E8%B4%A1%E7%8C%AE

**Comment by wangzhipeng404** [comment]
我测试一了一下，具体报错位置为 uditor.all.js 7516行的正则表达式
```
domUtils.on(doc, ['input'], function(e) {
                var reg = /[\u{1f300}-\u{1f5ff}\u{1f900}-\u{1f9ff}\u{1f600}-\u{1f64f}\u{1f680}-\u{1f6ff}\u{2600}-\u{26ff}\u{2700}-\u{27bf}\u{1f1e6}-\u{1f1ff}\u{1f191}-\u{1f251}\u{1f004}\u{1f0cf}\u{1f170}-\u{1f171}\u{1f17e}-\u{1f17f}\u{1f18e}\u{3030}\u{2b50}\u{2b55}\u{2934}-\u{2935}\u{2b05}-\u{2b07}\u{2b1b}-\u{2b1c}\u{3297}\u{3299}\u{303d}\u{00a9}\u{00ae}\u{2122}\u{23f3}\u{24c2}\u{23e9}-\u{23ef}\u{25b6}\u{23f8}-\u{23fa}]/gu;
                if (e.data && reg.test(e.data)){
                    me.fireEvent('contentchange');
                }
            });
```
chrome 49好像不支持 u 这种匹配模式
报错信息为 Uncaught SyntaxError: Invalid regular expression flags

**Comment by YaoKaiLun** [comment]
@wangzhipeng404 chrome 50 以下正则的确不支持 unicode flag

**Comment by wangzhipeng404** [comment]
我如果删除该这个flag是能够正常加载编辑器的，就是不确定副作用，请问这个正则的作用是什么，我移除unicode flag影响大吗，如果影响不大我可以自己针对浏览器版本进行修改

**Comment by wangzhipeng404** [comment]
我用babel把正则转化了一下，运行貌似没问题了
`var reg = /(?:[\xA9\xAE\u2122\u23E9-\u23EF\u23F3\u23F8-\u23FA\u24C2\u25B6\u2600-\u27BF\u2934\u2935\u2B05-\u2B07\u2B1B\u2B1C\u2B50\u2B55\u3030\u303D\u3297\u3299]|\uD83C[\uDC04\uDCCF\uDD70\uDD71\uDD7E\uDD7F\uDD8E\uDD91-\uDE51\uDF00-\uDFFF]|\uD83D[\uDC00-\uDE4F\uDE80-\uDEFF]|\uD83E[\uDD00-\uDDFF])/g;`

**Comment by wangzhipeng404** [comment]
能替换掉是最好的了，不用每次升级自己打包了

kailunyao <notifications@github.com>于2018年12月4日 周二18:23写道：

**Comment by YaoKaiLun** [comment]
@wangzhipeng404 已替换，你可以升级到 1.7.1 版本试下

**Comment by wangzhipeng404** [comment]
好的，明天试试，顺便测试一下

kailunyao <notifications@github.com>于2018年12月4日 周二18:37写道：
