### ISSUE TITLE
刚运行报错

### ISSUE THREAD

**Issue by zuilafeng** [ifanrx/react-ueditor#26]
TypeError: Cannot read property 'then' of undefined
ReactUeditor.componentDidMount
node_modules/ifanrx-react-ueditor/lib/ReactUeditor.js:379
  376 |   });
  377 | }
  378 | 
> 379 | window.UE_LOADING_PROMISE.then(function () {
  380 |   _this2.tempfileInput = document.getElementById(_this2.fileInputID);
  381 | 
  382 |   _this2.initEditor();

**Comment by YaoKaiLun** [comment]
@zuilafeng  ueditor 成功引入了吗

**Comment by CSZRZ** [comment]
@zuilafeng 你好，请教下这个问题怎么解决的呢？我也遇到了一样的问题
