### ISSUE TITLE
上传视频之后无法显示在编辑器中

### ISSUE THREAD

**Issue by fangzongwu** [ifanrx/react-ueditor#27]

**Comment by YaoKaiLun** [comment]
@fangzongwu 控制台有报什么错吗？截一下图，或者自己审查一下元素看看

**Comment by fangzongwu** [comment]
![image](https://user-images.githubusercontent.com/19547559/52616324-2974ac00-2ed3-11e9-9777-5fd65934cccc.png)
你好，没有生成video标签

**Comment by fangzongwu** [comment]
点击‘直接上传’按钮，然后提交，没有生成video标签，但是添加链接是可以生成的

**Comment by YaoKaiLun** [comment]
@fangzongwu 你是不是少写了上传视频的逻辑？

**Comment by fangzongwu** [comment]
@YaoKaiLun 我检查了一下，是我操作有误，应该点击添加之后才能插入。
