### ISSUE TITLE
结合ANTD Form.Item使用时会出现光标一直再最左边的情况

### ISSUE THREAD

**Issue by Colorul** [ifanrx/react-ueditor#38]

**Comment by cilla123** [comment]
请问解决了吗？也碰到同一样的问题

**Comment by Colorul** [comment]
@cilla123 没在使用ANTD 的双向绑定 就不会出现这个问题
`            <Form.Item {...formContentItemLayout} label="内容">
              <ReactUeditor
                ueditorPath="/ueditor"
                plugins={['uploadImage']}
                uploadImage={this.uploadImage}
                getRef={this.getUeditor}
              />
            </Form.Item>`

获取的时候直接使用 引用获取富文本内容即可 let content = this.ueditorRef.getContent();

**Comment by chencl1986** [comment]
将trigger改为onBlue就可以了。

```
<FormItem label={'内容'}>
  {form.getFieldDecorator('Content', {
     trigger: 'onBLue',
     validateTrigger: 'onBLue',
   })(<ReactUEditor />)}
</FormItem>
```

**Comment by Colorul** [comment]
已转行，关闭issue
