### ISSUE TITLE
同时按下ctrl和回车键，网址会跳转到形如 xxxx?reactueditorxxx= 的地址

### ISSUE THREAD

**Issue by GYxiaOZ** [ifanrx/react-ueditor#40]
当焦点在编辑器上的时候，同时按下ctrl和回车键，网址会跳转到形如 xxxx?reactueditorxxx= 的地址

**Comment by unrealsmart** [comment]
这个问题的主要原因是`ueditor.all.js`文件中注册了`autosubmit`插件，此插件用于手动提交，如果你将集成在表单中，按`CTRL+回车键`会触发表单提交。

因此目前有两种方案可解决：

1. 注释`ueditor.all.js`中注册`autosubmit`插件的代码
2. 使用`react-ueditor`(需要自己将这个项目`clone`到本地修改)，在`src/ReactUeditor.js`中的`initEditor`中添加如下代码：
```
window.UE.plugin.register("autosubmit", () => ({
  shortcutkey: {
    autosubmit: "ctrl+13" //手动提交
  },
  commands: {
    autosubmit: {
      execCommand: () => {},
    }
  }
}));
```
重写`autosubmit`插件

**Comment by GYxiaOZ** [comment]
感谢老哥，我已经fork项目解决了此问题
