### ISSUE TITLE
不要鼠标拖动改变大小功能

### ISSUE THREAD

**Issue by wangdongdong9264** [ifanrx/react-ueditor#42]
能否去掉鼠标拖动改变图片大小大小功能 
"ifanrx-react-ueditor": "^1.5.1",
"react": "^15.6.2",

**Comment by PluviaCon** [comment]
这个是UE默认的功能...

**Comment by wangdongdong9264** [comment]
既然去不掉 那我能让它根据图片的宽高 等比例缩放
有思路或更好的插件吗
谢谢
