### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by wangdongdong9264** [ifanrx/react-ueditor#9]
`uploadImage`  这个能支持多图上传吗

**Comment by YaoKaiLun** [comment]
使用 multipleImagesUpload={true} 开启多图片上传支持

**Comment by wangdongdong9264** [comment]
谢谢你的回答 但是加了后还是没有开启多图片上传 
`import React,{Component} from 'react';
import {Button} from 'antd';
import ReactUeditor from 'ifanrx-react-ueditor';
import {upload_image} from "../../axios/config";  
import Editor from 'react-umeditor';


class ueditorTest extends Component{
    constructor(props){
        super(props)
        this.state={
            Uploads:true
        }
        this.ueditor=undefined
    }

    componentDidMount(){

    }

    uploadImage = e => {
        console.log(e.target.files)
        return new Promise(function(resolve, reject) {
            let file = e.target.files[0]
            // console.log(file)

            const xhr = new XMLHttpRequest(); // eslint-disable-line no-undef
            xhr.open('POST', upload_image);
            const data = new FormData(); // eslint-disable-line no-undef
            data.append('image', file);
            xhr.send(data);
            xhr.addEventListener('load', () => {
                const response = JSON.parse(xhr.responseText);
                // console.log(response)
                resolve(response.info.url)
            });

        })
    }

    getUeditor = ref => {
        this.ueditor = ref
    }
    getEditorContent = () => {
        console.log(this.ueditor.getContent())
    }


    // react-umeditor
    uploadImageCallback = (file) => {
        console.log(file)


        return new Promise(function(resolve, reject) {
            // let file = e.target.files[0]
            // console.log(file)

            const xhr = new XMLHttpRequest(); // eslint-disable-line no-undef
            xhr.open('POST', 'http://api.hbase.hapi123.net/upload2/image');
            const data = new FormData(); // eslint-disable-line no-undef
            data.append('image', file);
            xhr.send(data);
            xhr.addEventListener('load', () => {
                const response = JSON.parse(xhr.responseText);
                // console.log(response)
                resolve({data: {image_src: response.info.url}, status: response.info.url ? 'success' : 'error'}  )
            });

        })
    }




    render(){
        const {Uploads}=this.state;

        return(
            <div style={{width:'100%'}}>
                <Button onClick={this.getEditorContent}>获取内容</Button>
                <div style={{width:600}}>
                    <ReactUeditor
                        getRef={this.getUeditor}
                        config={{zIndex: 1001}}
                        plugins={['uploadImage', 'insertCode']}
                        multipleImagesUpload={Uploads}
                        uploadImage={this.uploadImage}
                        ueditorPath='./ueditor'
                    />

                    {/*<Editor*/}
                        {/*uploadImageCallback={this.uploadImageCallback}*/}
                    {/*/>*/}

                </div>

            </div>
        )
    }

}

export default ueditorTest;`

**Comment by wangdongdong9264** [comment]
`./ueditor`   是 `node_modules\ifanrx-react-ueditor\vendor\ueditor`目录下的

**Comment by YaoKaiLun** [comment]
你看下装的是哪个版本的？

**Comment by wangdongdong9264** [comment]
"ifanrx-react-ueditor": "^1.4.2"

**Comment by wangdongdong9264** [comment]
"antd": "^3.0.1",
"react": "^15.6.2",

**Comment by YaoKaiLun** [comment]
需要 1.5.0 或以上版本才可以哦

**Comment by YaoKaiLun** [comment]
最新的版本 1.5.1 也已上传上 npm ，你删掉重新装一下哈

**Comment by aa7633285** [comment]
你好，为什么我使用了。但是页面显示不出来呢

**Comment by wangdongdong9264** [comment]
能否发一下你的代码 
Please provide the code

**Comment by wangdongdong9264** [comment]
或者描述清楚
be fully described

**Comment by aa7633285** [comment]
我的项目中 yarn add ifanrx-react-ueditor 了， 
import React, { Component } from 'react';
import { Input } from 'antd';
import ReactUeditor from 'ifanrx-react-ueditor';
import './index.less';
导入了  然后在下面使用
<ReactUeditor
                    config={{zIndex: 1001}}
                    ueditorPath="/static/uf8-php"
                    value="Hello World!"
                    multipleImagesUpload={false}
                />
但是在页面上只有<script id="reactueditor0.c55bgwqux6u" name="reactueditor0.c55bgwqux6u" type="text/plain"></script> 标签和 <input type="file" id="fileinput0.cymi4jt42eb" style="visibility: hidden;">  但是没有内容   空白的

**Comment by aa7633285** [comment]
版本是1.51

**Comment by aa7633285** [comment]
我想了一下应该是 ueditorPath 路径有问题  我想问的是  我是复制的这个项目这个项目中vendor直接放在项目中的  我的这个路径该怎么用

**Comment by wangdongdong9264** [comment]
我是放在了项目的 public 静态文件夹下面 然后就是按照上面代码引入的
注意一下 打包后 可能会出现刷新一下页面编辑器就消失的情况 f12看一下有哪些文件路径错误 在vendor\ueditor目录下将对应的文件复制一下

**Comment by aa7633285** [comment]
ueditor.config.js  报404  但是我的路径是对的啊

**Comment by wangdongdong9264** [comment]
把错误截图发一下

**Comment by aa7633285** [comment]
报的错就是本地请求  http://localhost:3006/utils/vendor/ueditor/ueditor.config.js   文件 404  请求不到 ueditor.config.js 文件。不能初始化

**Comment by wangdongdong9264** [comment]
ueditorPath的路径
ueditor文件路径
show me

**Comment by wangdongdong9264** [comment]
你看一下自己的路径下面有没有这个文件 没有就复制一份

**Comment by aa7633285** [comment]
我现在是只把vendor文件夹复制到我的项目了，放在src里面的utils里面  然后E:\smart-customer-service\src\utils\vendor\ueditor   这是ueditor的路径     我引用文件的路径是E:\smart-customer-service\src\compnents\knowledge\index.js      ueiditorPath 写的是 ../../utils/vendor/ueditor      这样就报404

**Comment by aa7633285** [comment]
@wangdongdong9264   大神  麻烦帮我看下

**Comment by wangdongdong9264** [comment]
不要放在src里 
你的 index.html 在哪就放在那

**Comment by aa7633285** [comment]
这个项目没有index.html  现在已经搞定了。这个上传图片到服务器是需要在uploadImage 这个方法里面发送数据么？后台说配置后台上传接口就可以了？不知道你那是怎么做的

**Comment by wangdongdong9264** [comment]
对的 多个图片上传改成Promise.all上传

**Comment by aa7633285** [comment]
你那边是在uploadImage 这个方法里上传的？那上传好的图片什么的，能在编辑器里面显示么？

**Comment by wangdongdong9264** [comment]
我想知道你的路径是怎么解决的

**Comment by wangdongdong9264** [comment]
能呀

**Comment by aa7633285** [comment]
ueditorPath={process.env.PUBLIC_URL + '/vendor/ueditor'}   我放在src同级的public文件夹里面

**Comment by wangdongdong9264** [comment]
resolve(response.info.url)    response.info.url上传成功返回图片的url

**Comment by 17398935380gtt** [comment]
我安照上面提供的方法，

**Comment by 17398935380gtt** [comment]
我按照上面提供的方法：yarn add ifanrx-react-ueditor ，然后引入组件
报错了
Uncaught SyntaxError: Unexpected token <
ueditor.all.min.js:1 Uncaught SyntaxError: Unexpected token <
ReactUeditor.js:227 Uncaught (in promise) TypeError: Cannot read property 'getEditor' of undefined
    at ReactUeditor._this.initEditor (ReactUeditor.js:227)
    at ReactUeditor.js:289
能帮我看看吗？
我吧文件放进build里也不行

**Comment by YaoKaiLun** [comment]
@17398935380gtt 应该是你的 ueditor 路径没配对，找不到 ueditor，你在控制台输入  window.UE 看看是不是 undefined

**Comment by 17398935380gtt** [comment]
@YaoKaiLun 控制台里输入window.UE什么都不显示，就是空白的

**Comment by YaoKaiLun** [comment]
@17398935380gtt 你确认一下 ueditorPath="/static/uf8-php" 这个有没有配正确

**Comment by YaoKaiLun** [comment]
这个你要看开发文档了 https://github.com/ifanrx/react-ueditor

**Comment by 17398935380gtt** [comment]
@aa7633285 
我按照上面的方法，吧ueditor 放在public里，然后引用
    ueditorPath="../public/ueditor"
可是页面还是空白的，能帮我看看吗

**Comment by 17398935380gtt** [comment]
@YaoKaiLun 
我把ueditor放到public下，然后引用
                  ueditorPath="../public/ueditor" 
可是页面上还是什么都没，能帮我看看吗？

**Comment by YaoKaiLun** [comment]
@17398935380gtt 控制台有报什么错吗？

**Comment by YaoKaiLun** [comment]
@17398935380gtt 看下控制台的报错，再测试在控制台输入 window.UE 是否有值，如果没有，可能是你的构建过程影响到了路径的映射

**Comment by 17398935380gtt** [comment]
@YaoKaiLun 
有报错的，
Uncaught SyntaxError: Unexpected token <
ueditor.all.min.js:9 Uncaught Error: not import language file
    at UE.Editor.getLang (ueditor.all.min.js:9)
    at UE.Editor.UE.plugins.autofloat (ueditor.all.min.js:13)
    at ueditor.all.min.js:9
    at Object.each (ueditor.all.min.js:7)
    at Object.load (ueditor.all.min.js:9)
    at ueditor.all.min.js:8
    at HTMLScriptElement.i.onload.i.onreadystatechange (ueditor.all.min.js:7)
这个应该是路径不对，
我注销了    // config={{zIndex: 1001}}    就能运行出来了
还是希望能解决这个问题

**Comment by YaoKaiLun** [comment]
你试着用绝对路径看看是否正确

**Comment by YaoKaiLun** [comment]
@17398935380gtt 你试着用绝对路径看看是否正确
